Meenu/chore: added search under block
deriv-com/deriv-com-v2 pull request #111
Opened 2023-11-01 06:11 UTC by meenakshi-deriv

2023-11-02 07:16 UTC, mohsen-deriv commented
@meenakshi-deriv is this ready?

2023-11-02 07:17 UTC, mohsen-deriv requested changes
please resolve conflicts

2023-11-06 07:35 UTC, mohsen-deriv requested changes

2023-11-06 07:35 UTC, mohsen-deriv commented on libs/blocks/index.d.ts
> +export * from '../../dist/libs/blocks/deriv-com-v2/libs/blocks/src/index'
why do we need this?

2023-11-06 07:38 UTC, meenakshi-deriv commented on libs/blocks/index.d.ts
> +export * from '../../dist/libs/blocks/deriv-com-v2/libs/blocks/src/index'
strang. Not my changes. Let me check.

2023-11-06 07:50 UTC, prince-deriv commented on package.json
> +    "react-device-detect": "^2.2.3",
Let's remove this. It's not being used anymore.

2023-11-06 09:24 UTC, prince-deriv requested changes

2023-11-06 09:24 UTC, prince-deriv commented on libs/blocks/src/lib/search/index.tsx
> +  searchPlaceholder: string;
`placeholder` alone I think is enough 
```suggestion
  placeholder: string;
```

2023-11-06 09:51 UTC, merged