nuzhy/live market subtaks fix
deriv-com/deriv-com-v2 pull request #156
Opened 2023-11-14 06:24 UTC by Nuzhy-Deriv

fix for live market font-colors, sizes

2023-11-14 08:58 UTC, prince-deriv requested changes

2023-11-14 08:58 UTC, prince-deriv commented on libs/components/src/lib/card/live-market/buy-sell.buttons.tsx
> +        <Text size="sm" className={clsx(spreadClass(status))}>
I think we can omit `clsx` here

2023-11-14 09:16 UTC, prince-deriv requested changes

2023-11-14 09:16 UTC, prince-deriv commented on libs/components/src/lib/card/live-market/buy-sell.buttons.tsx
> +
```suggestion
const spreadClassname = status === 'closed'  ? 'text-typography-disabled' : 'text-typography-default';

```

2023-11-14 09:16 UTC, prince-deriv commented on libs/components/src/lib/card/live-market/buy-sell.buttons.tsx
> +        <Text size="sm" className={spreadClass(status)}>
```suggestion
        <Text size="sm" className={spreadClassname}>
```

2023-11-14 09:16 UTC, prince-deriv commented on libs/components/src/lib/card/live-market/buy-sell.buttons.tsx
> +        <Text size="sm" bold className={spreadClass(status)}>
Same here

2023-11-14 09:32 UTC, prince-deriv requested changes

2023-11-14 09:32 UTC, prince-deriv commented on libs/components/src/lib/card/live-market/index.tsx
> +import clsx from 'clsx';
```suggestion

```

2023-11-14 09:40 UTC, Nuzhy-Deriv commented on libs/components/src/lib/card/live-market/index.tsx
> +import clsx from 'clsx';
i'm using this `clsx` in line no 73

2023-11-15 03:20 UTC, mohsen-deriv approved these changes

2023-11-15 03:20 UTC, merged