Meenu/add storybook search block
deriv-com/deriv-com-v2 pull request #184
Opened 2023-11-20 08:26 UTC by meenakshi-deriv

Added story book for search block

2023-11-24 06:03 UTC, mohsen-deriv requested changes

2023-11-24 06:03 UTC, mohsen-deriv commented on libs/blocks/src/lib/search/search-block.stories.tsx
> +} from 'libs/templates/src/lib/help-center/sections/search/search-results';
please don't import this directly here, just provide your own data and pass it to story. thanks 🙏 
this way we might confuse people that they can make circular deps in modules and libs.

2023-11-28 06:02 UTC, meenakshi-deriv commented
Closing this PR as this will be fixed here https://github.com/deriv-com/deriv-com-v2/pull/205

2023-11-28 06:02 UTC, closed without merging

2023-11-28 06:02 UTC, meenakshi-deriv commented
Closing this PR as this will be fixed here https://github.com/deriv-com/deriv-com-v2/pull/205