Meenu/fix: chromatic issues fix on live price block
deriv-com/deriv-com-v2 pull request #200
Opened 2023-11-27 08:30 UTC by meenakshi-deriv

- Moved description from header section. Description is between card slider and link. 

-  Updated link component's text body to md .

2023-11-27 09:29 UTC, prince-deriv requested changes

2023-11-27 09:29 UTC, prince-deriv commented on libs/blocks/src/lib/live-market/index.tsx
> +            className={clsx('flex items-center justify-center text-body-md')}
Let's remove `clsx`

2023-11-27 10:45 UTC, mohsen-deriv commented
@prince-deriv I wanna merge this to main, is it ok? 
please advice

2023-11-27 15:39 UTC, jia-deriv approved these changes

2023-11-28 08:12 UTC, prince-deriv approved these changes

2023-11-28 08:28 UTC, prince-deriv approved these changes

2023-11-28 08:28 UTC, merged