chore: account comparison block
deriv-com/deriv-com-v2 pull request #76
Opened 2023-10-20 02:56 UTC by Nuzhy-Deriv

![image](https://github.com/deriv-com/deriv-com-v2/assets/125249108/20d62444-14cd-4e71-b85f-5a0813877ef6)

2023-10-24 17:00 UTC, mohsen-deriv requested changes

2023-10-24 17:00 UTC, mohsen-deriv commented on libs/components/src/lib/table/account-table/table2/index.tsx
> +export const AccountTable2: React.FC<AccountTableProps> = ({
this component is too huge, please break it down and create more small components.

2023-10-25 07:37 UTC, prince-deriv commented on libs/blocks/src/lib/account-comparison/index.tsx
> +      <FluidContainer className="flex flex-col items-center gap-gap-xl lg:gap-gap-2xl">
Aren't we using `gap-general`?

2023-10-26 02:26 UTC, mohsen-deriv approved these changes

2023-10-26 02:27 UTC, merged